### ISSUE TITLE
Figure out student image styling for student grid

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2016#12]
The desire is that they are greyscale, and on hover blended with the gradient pattern.

I believe this can be handled all with imgix.

**Comment by webmasterkai** [comment]
Yeah, let me know if you need help figuring out the url query params!

edit: [Are query params actually useful in this case?]

**Comment by bjornmeansbear** [comment]
I guess I just need to size the gradient for the overlay correctly, and then that needs to be somewhere on imgix so they can be blended – ala snelb :+1:

**Comment by bjornmeansbear** [comment]
we can just add &sat=-100 to the photo-url for regular grayscale...

and then the for the blend... still working on that.

So where in the props on Student.js can I make the two different states of the url? I do see the {photo.url}   and then down in the propTypes is see photo declared.

and do I need to make a "regular state" variable and then a "hover state" variable? where it would just include the same {photo.url} but just change the addendum?

**Comment by webmasterkai** [comment]
The only thing the component should worry about is displaying "regular" or "hover" and calling a function that tells the application if the image should toggle the state. I think we could pass the component a property like `displayId` so the component knows what image from the available options it should display. We'll also need to send a property like `toggleActive` that the component can call when the user hovers or leaves.

**Comment by bjornmeansbear** [comment]
here is the image for blending:
http://dbox.cape.io/7192159/cape/micagradshow/images/blend.jpg

here's the rough code....

https://assets.imgix.net/unsplash/bear.jpg?fit=crop&h=300&w=400&sat=-100&bm=multiply&blend=http%3A%2F%2Fdbox.cape.io%2F7192159%2Fcape%2Fmicagradshow%2Fimages%2Fblend.jpg&balph=80&bs=inherit

**Comment by bjornmeansbear** [comment]
I think this is solved. Slightly slower to load solution up front, but better performance on actual hover/rollover. 4002aba11f63c1434f18a45094c546679dbfcf5d
