### ISSUE TITLE
Create new component for noImages inside profile

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/mgs2016#18]
Create a new component file /src/compontents/profile/noImages.js
Copy over the contents of the render function of noImages.cjsx in grad-show-2015 to mgs-2016

**Comment by bjornmeansbear** [comment]
Is this completed?

**Comment by webmasterkai** [comment]
https://github.com/OOKB/mgs2016/blob/mockup/src/components/Profile/NoImages.js
