### ISSUE TITLE
Figure out what to do with embed.ly code for videos, etc.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2016#20]
https://www.dropbox.com/s/77r9rxq0nl6ps6m/Screenshot%202016-01-13%2022.38.32.png?dl=0
https://www.dropbox.com/s/r6dqwy19lkj1tvc/Screenshot%202016-01-13%2022.39.26.png?dl=0

I think the embedly iframe has a height/width, and it needs to not...
also, parent div needs some sort of class to be better targeted — embedly-wrapper?

**Comment by bjornmeansbear** [comment]
so I found where this gets printed out in `src > components > Profile > SlideShow.js`

lines 112–120 spit it out, it looks like `work.data.html` is where it comes from in the JSON

There doesn't look like there is anyway to control the height/width, etc. of the iframe in the react templates?

**Comment by webmasterkai** [comment]
You can set defaultProps https://github.com/OOKB/mgs2016/blob/mockup/src/components/Profile/Video.js or pass them via https://github.com/OOKB/mgs2016/blob/mockup/src/components/Profile/SlideThumb.js#L9

The props are things like width and height. We could make them dynamic or fixed or whatever you want.
