### ISSUE TITLE
Gallery Image Pixellation

### ISSUE THREAD

**Issue by davidharleydale** [OOKB/mgs2016#26]
When you click on a student, their gallery of images are very pixellated. 

This is true for all students.

<img width="1157" alt="screen shot 2016-01-18 at 2 18 42 pm" src="https://cloud.githubusercontent.com/assets/9080453/12400496/6c990430-bdee-11e5-9856-3f24e3e06e93.png">

**Comment by webmasterkai** [comment]
What's a reasonable image width size for this?

**Comment by davidharleydale** [comment]
Probably something around 800 though I uploaded an image with a 1200px width and it was resized to 400x289 and then scaled to 692x500

**Comment by webmasterkai** [comment]
changed artwork image size to 900 max width instead of 400.
