### ISSUE TITLE
Change Class names  

### ISSUE THREAD

**Issue by davidharleydale** [OOKB/mgs2016#27]
On the program-info clearfix mb2 undefined div, below that there is a div with offset-by-three text-center.

Can you remove offset-by-three and set text-center to text-left.

**Comment by bjornmeansbear** [comment]
So the program descriptions for when you sort students by program, those should just be left aligned text and stuck all the way to the left of the parent.

**Comment by davidharleydale** [comment]
Yup - nothing on the side is centered so I feel that's the best solution. Otherwise it looks slightly odd in the middle.
