### ISSUE TITLE
Map functionality

### ISSUE THREAD

**Issue by tlupfer** [OOKB/mgs2016#6]
@jaredv83 
### Things for Jared to do
- [x] Use npm to install the package "google-map-react"
- [x] Commit and push your change
- [x] Fire up the development server for this repo using npm run [correct script name here]
- [x] Open your browser and load the page
- [x] Scroll down to the area where we will be putting a map
- [x] import the google-map-react component to src/components/Galleries/Gallerymap.js
- [x] Add a simple example from http://istarkov.github.io/google-map-react/map/simple in place of {'gmap'}
- [x] Commit and push your changes

**Comment by webmasterkai** [comment]
- [ ] GalleryMap component should accept `settings` object. Look for `location.lat` and `location.long` for centering information and pass this to the GoogleMap component using the example linked above
- [x] Fix the way props are sent to `ListingItem` within src/components/Galleries/GalleryListing.js
- [ ] GalleryMap component should accept `locations` array. Look for `location[].geoData.location.lat`. These will be used to generate pins on the map and contain the information to be shown when clicking on them

**Comment by bjornmeansbear** [comment]
This looks like it is all completed, using pins from new data source.
